# node port file
apiVersion: v1
kind: Service
metadata:
  name: client-node-port
spec:
  type: NodePort
  ports:
    - port: 3050 # Port is the port number which makes a service visible to other services running within the same K8s cluster. 
      targetPort: 3000 # Target port is the port on the POD where the service is running.
      nodePort: 31515 # Node port is the port on which the service can be accessed from external users using Kube-Proxy
  selector:
    component: web