# container file
# Prefer deployments over pods
# Rarely used directly in production (because of limitation around updating config to update pod name, port, number of pods etc)

apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    component: web
spec:
  containers:
    - name: client
      image: stephengrider/multi-client
      ports:
        - containerPort: 3000
