kind: Service
apiVersion: v1
metadata:
  # Unique key of the Service instance
  name: fleetman-webapp
spec:
  ports:
    # Accept traffic sent to port 80
    # On the browser, access localhost:30080
    - name: http
      port: 80
      nodePort: 30080
  selector:
    # Loadbalance traffic across Pods matching
    # this label selector
    # This defines which pods are going to be represented by this service.
    app: webapp
    # release: "0-5"
  # Create an HA proxy in the cloud provider
  # with an External IP address - *Only supported
  # by some cloud providers*
  type: NodePort

---
kind: Service
apiVersion: v1
metadata:
  name: fleetman-queue
spec:
  ports:
    - name: http
      port: 8161 # expose local port 8161 to the world outside on 30010
      nodePort: 30010
    - name: endpoint
      port: 61616
      
  selector:
    app: queue
  type: NodePort

---
kind: Service
apiVersion: v1
metadata:
  name: fleetman-position-tracker
spec:
  ports:
    - name: http
      port: 8080
      # nodePort: 30020
  selector:
    app: position-tracker 
  # type: NodePort
  type: ClusterIP
  # type: NodePort (use NodePort for testing 
  # via browser localhost:30020)

---
kind: Service
apiVersion: v1
metadata:
  name: fleetman-api-gateway
spec:
  selector:
    app: api-gateway
  ports:
  - name: http
    port: 8080
    # nodePort: 30020
  type: ClusterIP
  # for testing
  # type: NodePort
  # http://localhost:30020/
