apiVersion: v1
kind: Pod
metadata: 
  name: mysql
  labels:
    app: mysql
spec:
  containers:
    - name: mysql
      image: mysql:5
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: fleetman
---
apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
  type: ClusterIP

### 
# Test connectivity from webapp pod to database pod.
# Install mysql client on webapp pod.
# kubectl exec -it <podname> sh 
# nslookup database (should return database pod ip)
# apk update
# apk add mysql-client

# mysql -h database -uroot -ppassword fleetman
